specVersion: 1.0.0
schema:
  file: ../schema.graphql
indexerHints:
  prune: never
dataSources:
  ###
  # INITIALIZATION
  ###
  - kind: ethereum/contract
    name: InitVersion
    network: base
    source:
      address: "0xBA51AA60B3b8d9A36cc748a62Aa56801060183f8"
      abi: Aquifer
      startBlock: 22622966
      endBlock: 22622966
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Version
      abis:
        - name: Aquifer
          file: ../../../core/abis/Aquifer.json
      blockHandlers:
        - handler: handleInitVersion
          filter:
            kind: once
      file: ../src/utils/constants/Version.ts
  - kind: ethereum/contract
    name: InitInit
    network: base
    source:
      address: "0xBA51AA60B3b8d9A36cc748a62Aa56801060183f8"
      abi: Aquifer
      startBlock: 22622966
      endBlock: 22622966
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Version
      abis:
        - name: Aquifer
          file: ../../../core/abis/Aquifer.json
      blockHandlers:
        - handler: init
          filter:
            kind: once
      file: ../src/utils/init/PintoInit.ts
  ###
  # BASIN
  ###
  - kind: ethereum/contract
    name: Aquifer
    network: base
    source:
      address: "0xBA51AA60B3b8d9A36cc748a62Aa56801060183f8"
      abi: Aquifer
      startBlock: 22622966
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Aquifer
      abis:
        - name: Aquifer
          file: ../../../core/abis/Aquifer.json
        - name: ERC20
          file: ../../../core/abis/ERC20.json
      eventHandlers:
        - event: BoreWell(address,address,address[],(address,bytes),(address,bytes)[],bytes)
          handler: handleBoreWell
      file: ../src/handlers/AquiferTemplateHandler.ts
  # - kind: ethereum/contract
  #   name: HourlySnapshotPolling
  #   network: base
  #   source:
  #     address: "0xBA51AA60B3b8d9A36cc748a62Aa56801060183f8"
  #     abi: Aquifer
  #     startBlock: 22623515 # Initial liquidity added + 1
  #   mapping:
  #     kind: ethereum/events
  #     apiVersion: 0.0.7
  #     language: wasm/assemblyscript
  #     entities:
  #       - Well
  #     abis:
  #       - name: Aquifer
  #         file: ../../../core/abis/Aquifer.json
  #     blockHandlers:
  #       - handler: handleBlock
  #         filter:
  #           kind: polling
  #           every: 30 # 1 minute on base
  #     file: ../src/handlers/HourlySnapshotHandler.ts
  - kind: ethereum/contract
    name: BeanstalkEvents
    network: base
    source:
      address: "0xD1A0D188E861ed9d15773a2F3574a2e94134bA8f"
      abi: PintoPI13
      startBlock: 22622961 # Pintostalk Deployment
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Season
      abis:
        - name: PintoPI13
          file: ../../../core/abis/Beanstalk/Pinto-PI13.json
      eventHandlers:
        - event: Sunrise(indexed uint256)
          handler: handleBeanstalkSunrise
        - event: DewhitelistToken(indexed address)
          handler: handleDewhitelistToken
        # New signature in PI-12
        - event: Convert(indexed address,address,address,uint256,uint256,uint256,uint256)
          handler: handleConvert
      file: ../src/handlers/BeanstalkHandler.ts
  - kind: ethereum/contract
    name: LegacySilo-PintoLaunch-PintoPI13
    network: base
    source:
      address: "0xD1A0D188E861ed9d15773a2F3574a2e94134bA8f"
      abi: PintoLaunch
      startBlock: 22622961 # Pintostalk Deployment
      endBlock: 999999999 # PI-12 Deployment (TODO: enter actual value once known)
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Silo
      abis:
        - name: PintoLaunch
          file: ../../../core/abis/Beanstalk/Pinto-Launch.json
      eventHandlers:
        - event: Convert(indexed address,address,address,uint256,uint256)
          handler: handleConvert
      file: ../src/handlers/legacy/LegacyBeanstalkHandler.ts
templates:
  - kind: ethereum/contract
    name: Well
    network: base
    source:
      abi: Well
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Well
      abis:
        - name: Well
          file: ../../../core/abis/Well.json
        - name: WellFunction
          file: ../../../core/abis/WellFunction.json
        - name: PintoPI13
          file: ../../../core/abis/Beanstalk/Pinto-PI13.json
        - name: BeanstalkPrice
          file: ../../../core/abis/PintostalkPrice.json
        - name: ERC20
          file: ../../../core/abis/ERC20.json
        # Necessary to handle the case where BeanstalkPrice contract is not functioning. This contract isn't relevant
        # to Pinto (and will revert), but is kept to be compatible with legacy Beanstalk indexing.
        - name: CurvePrice
          file: ../../../core/abis/CurvePrice.json
      eventHandlers:
        - event: AddLiquidity(uint256[],uint256,address)
          handler: handleAddLiquidity
        - event: RemoveLiquidity(uint256,uint256[],address)
          handler: handleRemoveLiquidity
        - event: RemoveLiquidityOneToken(uint256,address,uint256,address)
          handler: handleRemoveLiquidityOneToken
        - event: Swap(address,address,uint256,uint256,address)
          handler: handleSwap
        - event: Shift(uint256[],address,uint256,address)
          handler: handleShift
        - event: Sync(uint256[],uint256,address)
          handler: handleSync
      file: ../src/handlers/WellHandler.ts
# features:
#   - grafting
# graft:
#   base: QmVMUL5PfmNH945M2nXq83KQXSpo5cSW9GsVigCFHLRRL4
#   block: 35280000
