# This file exists solely for the purpose of facilitating all codegen in a shared location such that all ABIs
# or templates are expanded independently of being used in all chains. Most of the information here is irrelevant,
# the only important part is in the `abis` and `templates` sections.
#  - For abis, its only the list of abis that is relevant. The name of the dataSource is also visible.
#  - For templates, it is only the name of the template that is relevant.
specVersion: 0.0.9
schema:
  file: ../schema.graphql
dataSources:
  # Silo V3
  - kind: ethereum/contract
    name: Beanstalk-ABIs
    network: not_relevant
    source:
      address: "0xC1E088fC1323b20BCBee9bd1B9fC9546db5624C5"
      abi: SiloV3
      startBlock: 17636279
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Silo-V3
      abis:
        - name: PreReplant
          file: ../../../core/abis/Beanstalk/Beanstalk-Pre-Replant.json
        - name: Replanted
          file: ../../../core/abis/Beanstalk/Beanstalk-Replanted.json
        - name: MarketV2
          file: ../../../core/abis/Beanstalk/Beanstalk-BIP29.json
        - name: SiloV3
          file: ../../../core/abis/Beanstalk/Beanstalk-BIP36.json
        - name: BasinBip
          file: ../../../core/abis/Beanstalk/Beanstalk-BIP37.json
        - name: SeedGauge
          file: ../../../core/abis/Beanstalk/Beanstalk-BIP45.json
        - name: Reseed
          file: ../../../core/abis/Beanstalk/Beanstalk-BIP50.json
        - name: PintoLaunch
          file: ../../../core/abis/Beanstalk/Pinto-Launch.json
        - name: PintoPI8
          file: ../../../core/abis/Beanstalk/Pinto-PI8.json
        - name: ERC20
          file: ../../../core/abis/ERC20.json
        - name: CurvePrice
          file: ../../../core/abis/CurvePrice.json
        - name: BeanstalkPrice
          file: ../../../core/abis/PintostalkPrice.json
        - name: CurvePrice
          file: ../../../core/abis/CurvePrice.json
        - name: Fertilizer
          file: ../../../core/abis/Fertilizer.json
        - name: WrappedSiloERC20
          file: ../../../core/abis/WrappedSiloERC20.json
        - name: SiloHelpers
          file: ../../../core/abis/SiloHelpers.json
      blockHandlers:
        - handler: handleInitVersion
          filter:
            kind: once
      file: ../src/utils/constants/Version.ts
