specVersion: 1.0.0
schema:
  file: ../schema.graphql
indexerHints:
  prune: never
dataSources:
  ###
  # INITIALIZATION
  ###
  - kind: ethereum/contract
    name: InitVersion
    network: base
    source:
      address: "0xD1A0D188E861ed9d15773a2F3574a2e94134bA8f"
      abi: PintoLaunch
      startBlock: 22622961 # Pintostalk Deployment
      endBlock: 22622961 # Pintostalk Deployment
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Version
      abis:
        - name: PintoLaunch
          file: ../../../core/abis/Beanstalk/Pinto-Launch.json
      blockHandlers:
        - handler: handleInitVersion
          filter:
            kind: once
      file: ../src/utils/constants/Version.ts
  - kind: ethereum/contract
    name: InitSnapshots
    network: base
    source:
      address: "0xD1A0D188E861ed9d15773a2F3574a2e94134bA8f"
      abi: PintoLaunch
      startBlock: 22622962 # Pintostalk Deployment + 1
      endBlock: 22622962 # Pintostalk Deployment + 1
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Beanstalk
      abis:
        - name: PintoLaunch
          file: ../../../core/abis/Beanstalk/Pinto-Launch.json
      blockHandlers:
        - handler: init
          filter:
            kind: once
      file: ../src/utils/init/PintoInit.ts
  - kind: ethereum/contract
    name: PI6Adjustment
    network: base
    source:
      address: "0xD1A0D188E861ed9d15773a2F3574a2e94134bA8f"
      abi: PintoLaunch
      startBlock: 27514420 # PI-6
      endBlock: 27514420 # PI-6
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Beanstalk
      abis:
        - name: PintoLaunch
          file: ../../../core/abis/Beanstalk/Pinto-Launch.json
      blockHandlers:
        - handler: processMissingEvents
          filter:
            kind: once
      file: ../src/utils/init/PI6Adjustment.ts
  ###
  # SILO
  ###
  - kind: ethereum/contract
    name: Silo
    network: base
    source:
      address: "0xD1A0D188E861ed9d15773a2F3574a2e94134bA8f"
      abi: PintoPI8
      startBlock: 22622961 # Pintostalk Deployment
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Silo
      abis:
        - name: PintoPI8
          file: ../../../core/abis/Beanstalk/Pinto-PI8.json
      eventHandlers:
        - event: AddDeposit(indexed address,indexed address,int96,uint256,uint256)
          handler: handleAddDeposit
        - event: RemoveDeposit(indexed address,indexed address,int96,uint256,uint256)
          handler: handleRemoveDeposit
        - event: RemoveDeposits(indexed address,indexed address,int96[],uint256[],uint256,uint256[])
          handler: handleRemoveDeposits
        - event: Convert(indexed address,address,address,uint256,uint256)
          handler: handleConvert
        - event: StalkBalanceChanged(indexed address,int256,int256)
          handler: handleStalkBalanceChanged
        - event: Plant(indexed address,uint256)
          handler: handlePlant
        - event: WhitelistToken(indexed address,bytes4,uint40,uint256,uint128,uint64)
          handler: handleWhitelistToken
        - event: UpdateWhitelistStatus(address,uint256,bool,bool,bool,bool)
          handler: handleUpdateWhitelistStatus
        - event: DewhitelistToken(indexed address)
          handler: handleDewhitelistToken
        - event: UpdatedStalkPerBdvPerSeason(indexed address,uint40,uint32)
          handler: handleUpdatedStalkPerBdvPerSeason
        - event: ClaimPlenty(indexed address,address,uint256)
          handler: handleClaimPlenty
        - event: ConvertDownPenalty(address,uint256,uint256)
          handler: handleConvertDownPenalty
      file: ../src/handlers/SiloHandler.ts
  ###
  # SEED GAUGE
  ###
  - kind: ethereum/contract
    name: SeedGauge
    network: base
    source:
      address: "0xD1A0D188E861ed9d15773a2F3574a2e94134bA8f"
      abi: PintoPI8
      startBlock: 22622961 # Pintostalk Deployment
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - SeedGauge
      abis:
        - name: PintoPI8
          file: ../../../core/abis/Beanstalk/Pinto-PI8.json
        - name: BeanstalkPrice
          file: ../../../core/abis/PintostalkPrice.json
      eventHandlers:
        - event: BeanToMaxLpGpPerBdvRatioChange(indexed uint256,uint256,int80)
          handler: handleBeanToMaxLpGpPerBdvRatioChange
        - event: GaugePointChange(indexed uint256,indexed address,uint256)
          handler: handleGaugePointChange
        - event: UpdateAverageStalkPerBdvPerSeason(uint256)
          handler: handleUpdateAverageStalkPerBdvPerSeason
        - event: FarmerGerminatingStalkBalanceChanged(indexed address,int256,uint8)
          handler: handleFarmerGerminatingStalkBalanceChanged
        - event: TotalGerminatingBalanceChanged(uint256,indexed address,int256,int256)
          handler: handleTotalGerminatingBalanceChanged
        - event: TotalGerminatingStalkChanged(uint256,int256)
          handler: handleTotalGerminatingStalkChanged
        - event: TotalStalkChangedFromGermination(int256,int256)
          handler: handleTotalStalkChangedFromGermination
        - event: UpdatedOptimalPercentDepositedBdvForToken(indexed address,uint64)
          handler: handleUpdatedOptimalPercentDepositedBdvForToken
      file: ../src/handlers/SeedGaugeHandler.ts
  ###
  # FIELD
  ###
  - kind: ethereum/contract
    name: Field
    network: base
    source:
      address: "0xD1A0D188E861ed9d15773a2F3574a2e94134bA8f"
      abi: PintoPI8
      startBlock: 22622961 # Pintostalk Deployment
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Field
      abis:
        - name: PintoPI8
          file: ../../../core/abis/Beanstalk/Pinto-PI8.json
        - name: BeanstalkPrice
          file: ../../../core/abis/PintostalkPrice.json
      eventHandlers:
        - event: Sow(indexed address,uint256,uint256,uint256,uint256)
          handler: handleSow
        - event: Harvest(indexed address,uint256,uint256[],uint256)
          handler: handleHarvest
        - event: PlotTransfer(indexed address,indexed address,uint256,indexed uint256,uint256)
          handler: handlePlotTransfer
        - event: TemperatureChange(indexed uint256,uint256,int32,uint256)
          handler: handleTemperatureChange
      file: ../src/handlers/FieldHandler.ts
  - kind: ethereum/contract
    name: LegacyField-PintoLaunch-PintoPI5
    network: base
    source:
      address: "0xD1A0D188E861ed9d15773a2F3574a2e94134bA8f"
      abi: PintoLaunch
      startBlock: 22622961 # Pintostalk Deployment
      endBlock: 24504478 # PI-5
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Field
      abis:
        - name: PintoLaunch
          file: ../../../core/abis/Beanstalk/Pinto-Launch.json
        - name: BeanstalkPrice
          file: ../../../core/abis/PintostalkPrice.json
      eventHandlers:
        - event: TemperatureChange(indexed uint256,uint256,int8,uint256)
          handler: handleTemperatureChange_v2
      file: ../src/handlers/legacy/LegacyFieldHandler.ts
  ###
  # MARKETPLACE
  ###
  - kind: ethereum/contract
    name: Marketplace
    network: base
    source:
      address: "0xD1A0D188E861ed9d15773a2F3574a2e94134bA8f"
      abi: PintoPI8
      startBlock: 22622961 # Pintostalk Deployment
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - PodMarketplace
      abis:
        - name: PintoPI8
          file: ../../../core/abis/Beanstalk/Pinto-PI8.json
      eventHandlers:
        - event: PodListingCreated(indexed address,uint256,uint256,uint256,uint256,uint24,uint256,uint256,uint8)
          handler: handlePodListingCreated
        - event: PodListingFilled(indexed address,indexed address,uint256,uint256,uint256,uint256,uint256)
          handler: handlePodListingFilled
        - event: PodOrderCreated(indexed address,bytes32,uint256,uint256,uint24,uint256,uint256)
          handler: handlePodOrderCreated
        - event: PodOrderFilled(indexed address,indexed address,bytes32,uint256,uint256,uint256,uint256,uint256)
          handler: handlePodOrderFilled
        - event: PodListingCancelled(indexed address,uint256,uint256)
          handler: handlePodListingCancelled
        - event: PodOrderCancelled(indexed address,bytes32)
          handler: handlePodOrderCancelled
      file: ../src/handlers/MarketplaceHandler.ts
  ###
  # SEASON
  ###
  - kind: ethereum/contract
    name: Season
    network: base
    source:
      address: "0xD1A0D188E861ed9d15773a2F3574a2e94134bA8f"
      abi: PintoPI8
      startBlock: 22622961 # Pintostalk Deployment
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Season
      abis:
        - name: PintoPI8
          file: ../../../core/abis/Beanstalk/Pinto-PI8.json
        - name: BeanstalkPrice
          file: ../../../core/abis/PintostalkPrice.json
        - name: WrappedSiloERC20
          file: ../../../core/abis/WrappedSiloERC20.json
      eventHandlers:
        - event: Sunrise(indexed uint256)
          handler: handleSunrise
        - event: Shipped(indexed uint32,uint256)
          handler: handleShipped
        - event: Receipt(indexed uint8,uint256,bytes)
          handler: handleReceipt
        - event: WellOracle(indexed uint32,address,int256,bytes)
          handler: handleWellOracle
        - event: Soil(indexed uint32,uint256)
          handler: handleSoil
        - event: SeasonOfPlentyField(uint256)
          handler: handlePlentyField
        - event: SeasonOfPlentyWell(indexed uint256,address,address,uint256,uint256)
          handler: handlePlentyWell
        - event: Incentivization(indexed address,uint256)
          handler: handleIncentive
      file: ../src/handlers/SeasonHandler.ts
  - kind: ethereum/contract
    name: LegacySeason-PintoLaunch-PintoPI5
    network: base
    source:
      address: "0xD1A0D188E861ed9d15773a2F3574a2e94134bA8f"
      abi: PintoLaunch
      startBlock: 22622961 # Pintostalk Deployment
      endBlock: 24504478 # PI-5
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Season
      abis:
        - name: PintoLaunch
          file: ../../../core/abis/Beanstalk/Pinto-Launch.json
      eventHandlers:
        - event: SeasonOfPlentyWell(indexed uint256,address,address,uint256)
          handler: handlePlentyWell_v1
      file: ../src/handlers/legacy/LegacySeasonHandler.ts
  ###
  # Gen Gauge
  ###
  - kind: ethereum/contract
    name: GenGauge
    network: base
    source:
      address: "0xD1A0D188E861ed9d15773a2F3574a2e94134bA8f"
      abi: PintoPI8
      startBlock: 27514420 # PI-6 Deployment
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - GenGauge
      abis:
        - name: PintoPI8
          file: ../../../core/abis/Beanstalk/Pinto-PI8.json
      eventHandlers:
        - event: Engaged(uint8,bytes)
          handler: handleEngaged
      file: ../src/handlers/GenGaugeHandler.ts
  ###
  # ERC20
  ###
  - kind: ethereum/contract
    name: Bean
    network: base
    source:
      address: "0xb170000aeeFa790fa61D6e837d1035906839a3c8"
      abi: ERC20
      startBlock: 22622961 # Pintostalk Deployment
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Season
      abis:
        - name: ERC20
          file: ../../../core/abis/ERC20.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleBeanTransfer
      file: ../src/handlers/TokenHandler.ts
  ###
  # Wrapped Deposit ERC20
  ###
  - kind: ethereum/contract
    name: sPinto
    network: base
    source:
      address: "0x00b174d66adA7d63789087F50A9b9e0e48446dc1"
      abi: WrappedSiloERC20
      startBlock: 27068608 # sPinto Deployment
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - WrappedSiloERC20
      abis:
        - name: WrappedSiloERC20
          file: ../../../core/abis/WrappedSiloERC20.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleWrappedDepositERC20Transfer
      file: ../src/handlers/WrappedSiloHandler.ts
  ###
  # Tractor
  ###
  - kind: ethereum/contract
    name: Tractor
    network: base
    source:
      address: "0xD1A0D188E861ed9d15773a2F3574a2e94134bA8f"
      abi: PintoPI8
      startBlock: 29064231 # PI-8 Deployment
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Tractor
      abis:
        - name: PintoPI8
          file: ../../../core/abis/Beanstalk/Pinto-PI8.json
      eventHandlers:
        - event: Tractor(indexed address,indexed address,indexed bytes32,uint256,uint256)
          handler: handleTractor
      file: ../src/handlers/TractorHandler.ts
  - kind: ethereum/contract
    name: TractorHelpers
    network: base
    source:
      address: "0x2808b14d287F8CA77eb25B16575aF187d5A05119"
      abi: TractorHelpers
      startBlock: 28930873 # TractorHelpers deployment
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Tractor
      abis:
        - name: TractorHelpers
          file: ../../../core/abis/TractorHelpers.json
      eventHandlers:
        - event: OperatorReward(uint8,indexed address,indexed address,address,int256)
          handler: handleOperatorReward
      file: ../src/handlers/TractorHandler.ts
# features:
#   - grafting
# graft:
#   base: QmaiSMSyNS2ACLJ5gXoMbqqYFennPzcHZj7ZYeGQFVJk5L
#   block: 27058608
